version: "3.8"

services:
  frontend:
    container_name: akgishark_frontend
    build: ./front-end
    restart: always
    ports:
      - "3000:3000"
  
  backend:
    container_name: akgishark_backend
    build: ./Back
    restart: always
    ports:
      - "8081:8080"